# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import iwf_pb2 as iwf__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in iwf_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlowServiceStub:
    """Hosted by iWF server; SDKs call these RPCs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartFlow = channel.unary_unary(
                '/iwf.FlowService/StartFlow',
                request_serializer=iwf__pb2.StartFlowRequest.SerializeToString,
                response_deserializer=iwf__pb2.StartFlowResponse.FromString,
                _registered_method=True)
        self.PublishToChannel = channel.unary_unary(
                '/iwf.FlowService/PublishToChannel',
                request_serializer=iwf__pb2.PublishToChannelRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StopFlow = channel.unary_unary(
                '/iwf.FlowService/StopFlow',
                request_serializer=iwf__pb2.StopFlowRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetAttributes = channel.unary_unary(
                '/iwf.FlowService/GetAttributes',
                request_serializer=iwf__pb2.GetAttributesRequest.SerializeToString,
                response_deserializer=iwf__pb2.GetAttributesResponse.FromString,
                _registered_method=True)
        self.SetAttributes = channel.unary_unary(
                '/iwf.FlowService/SetAttributes',
                request_serializer=iwf__pb2.SetAttributesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.LoadBlobs = channel.unary_unary(
                '/iwf.FlowService/LoadBlobs',
                request_serializer=iwf__pb2.LoadBlobsRequest.SerializeToString,
                response_deserializer=iwf__pb2.LoadBlobsResponse.FromString,
                _registered_method=True)
        self.WaitForFlow = channel.unary_unary(
                '/iwf.FlowService/WaitForFlow',
                request_serializer=iwf__pb2.WaitForFlowRequest.SerializeToString,
                response_deserializer=iwf__pb2.WaitForFlowResponse.FromString,
                _registered_method=True)
        self.SearchFlows = channel.unary_unary(
                '/iwf.FlowService/SearchFlows',
                request_serializer=iwf__pb2.SearchFlowsRequest.SerializeToString,
                response_deserializer=iwf__pb2.SearchFlowsResponse.FromString,
                _registered_method=True)
        self.ResetFlow = channel.unary_unary(
                '/iwf.FlowService/ResetFlow',
                request_serializer=iwf__pb2.ResetFlowRequest.SerializeToString,
                response_deserializer=iwf__pb2.ResetFlowResponse.FromString,
                _registered_method=True)
        self.InvokeRPC = channel.unary_unary(
                '/iwf.FlowService/InvokeRPC',
                request_serializer=iwf__pb2.InvokeRPCRequest.SerializeToString,
                response_deserializer=iwf__pb2.InvokeRPCResponse.FromString,
                _registered_method=True)
        self.SkipTimer = channel.unary_unary(
                '/iwf.FlowService/SkipTimer',
                request_serializer=iwf__pb2.SkipTimerRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateFlowConfig = channel.unary_unary(
                '/iwf.FlowService/UpdateFlowConfig',
                request_serializer=iwf__pb2.UpdateFlowConfigRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.WaitForStepCompletion = channel.unary_unary(
                '/iwf.FlowService/WaitForStepCompletion',
                request_serializer=iwf__pb2.WaitForStepCompletionRequest.SerializeToString,
                response_deserializer=iwf__pb2.WaitForStepCompletionResponse.FromString,
                _registered_method=True)
        self.WaitForAttribute = channel.unary_unary(
                '/iwf.FlowService/WaitForAttribute',
                request_serializer=iwf__pb2.WaitForAttributeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TriggerContinueAsNew = channel.unary_unary(
                '/iwf.FlowService/TriggerContinueAsNew',
                request_serializer=iwf__pb2.TriggerContinueAsNewRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/iwf.FlowService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=iwf__pb2.HealthInfo.FromString,
                _registered_method=True)


class FlowServiceServicer:
    """Hosted by iWF server; SDKs call these RPCs.
    """

    def StartFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishToChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAttributes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadBlobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitForFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchFlows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeRPC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SkipTimer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFlowConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitForStepCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitForAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerContinueAsNew(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.StartFlow,
                    request_deserializer=iwf__pb2.StartFlowRequest.FromString,
                    response_serializer=iwf__pb2.StartFlowResponse.SerializeToString,
            ),
            'PublishToChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishToChannel,
                    request_deserializer=iwf__pb2.PublishToChannelRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StopFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.StopFlow,
                    request_deserializer=iwf__pb2.StopFlowRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributes,
                    request_deserializer=iwf__pb2.GetAttributesRequest.FromString,
                    response_serializer=iwf__pb2.GetAttributesResponse.SerializeToString,
            ),
            'SetAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAttributes,
                    request_deserializer=iwf__pb2.SetAttributesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'LoadBlobs': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadBlobs,
                    request_deserializer=iwf__pb2.LoadBlobsRequest.FromString,
                    response_serializer=iwf__pb2.LoadBlobsResponse.SerializeToString,
            ),
            'WaitForFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitForFlow,
                    request_deserializer=iwf__pb2.WaitForFlowRequest.FromString,
                    response_serializer=iwf__pb2.WaitForFlowResponse.SerializeToString,
            ),
            'SearchFlows': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchFlows,
                    request_deserializer=iwf__pb2.SearchFlowsRequest.FromString,
                    response_serializer=iwf__pb2.SearchFlowsResponse.SerializeToString,
            ),
            'ResetFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetFlow,
                    request_deserializer=iwf__pb2.ResetFlowRequest.FromString,
                    response_serializer=iwf__pb2.ResetFlowResponse.SerializeToString,
            ),
            'InvokeRPC': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeRPC,
                    request_deserializer=iwf__pb2.InvokeRPCRequest.FromString,
                    response_serializer=iwf__pb2.InvokeRPCResponse.SerializeToString,
            ),
            'SkipTimer': grpc.unary_unary_rpc_method_handler(
                    servicer.SkipTimer,
                    request_deserializer=iwf__pb2.SkipTimerRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateFlowConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFlowConfig,
                    request_deserializer=iwf__pb2.UpdateFlowConfigRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'WaitForStepCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitForStepCompletion,
                    request_deserializer=iwf__pb2.WaitForStepCompletionRequest.FromString,
                    response_serializer=iwf__pb2.WaitForStepCompletionResponse.SerializeToString,
            ),
            'WaitForAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitForAttribute,
                    request_deserializer=iwf__pb2.WaitForAttributeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TriggerContinueAsNew': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerContinueAsNew,
                    request_deserializer=iwf__pb2.TriggerContinueAsNewRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=iwf__pb2.HealthInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iwf.FlowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iwf.FlowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlowService:
    """Hosted by iWF server; SDKs call these RPCs.
    """

    @staticmethod
    def StartFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/StartFlow',
            iwf__pb2.StartFlowRequest.SerializeToString,
            iwf__pb2.StartFlowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishToChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/PublishToChannel',
            iwf__pb2.PublishToChannelRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/StopFlow',
            iwf__pb2.StopFlowRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/GetAttributes',
            iwf__pb2.GetAttributesRequest.SerializeToString,
            iwf__pb2.GetAttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/SetAttributes',
            iwf__pb2.SetAttributesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadBlobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/LoadBlobs',
            iwf__pb2.LoadBlobsRequest.SerializeToString,
            iwf__pb2.LoadBlobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitForFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/WaitForFlow',
            iwf__pb2.WaitForFlowRequest.SerializeToString,
            iwf__pb2.WaitForFlowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchFlows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/SearchFlows',
            iwf__pb2.SearchFlowsRequest.SerializeToString,
            iwf__pb2.SearchFlowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/ResetFlow',
            iwf__pb2.ResetFlowRequest.SerializeToString,
            iwf__pb2.ResetFlowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeRPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/InvokeRPC',
            iwf__pb2.InvokeRPCRequest.SerializeToString,
            iwf__pb2.InvokeRPCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SkipTimer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/SkipTimer',
            iwf__pb2.SkipTimerRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFlowConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/UpdateFlowConfig',
            iwf__pb2.UpdateFlowConfigRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitForStepCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/WaitForStepCompletion',
            iwf__pb2.WaitForStepCompletionRequest.SerializeToString,
            iwf__pb2.WaitForStepCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitForAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/WaitForAttribute',
            iwf__pb2.WaitForAttributeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerContinueAsNew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/TriggerContinueAsNew',
            iwf__pb2.TriggerContinueAsNewRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.FlowService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            iwf__pb2.HealthInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub:
    """Hosted by iWF worker; server calls these RPCs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvokeWaitForMethod = channel.unary_unary(
                '/iwf.WorkerService/InvokeWaitForMethod',
                request_serializer=iwf__pb2.InvokeWaitForMethodRequest.SerializeToString,
                response_deserializer=iwf__pb2.InvokeWaitForMethodResponse.FromString,
                _registered_method=True)
        self.InvokeExecuteMethod = channel.unary_unary(
                '/iwf.WorkerService/InvokeExecuteMethod',
                request_serializer=iwf__pb2.InvokeExecuteMethodRequest.SerializeToString,
                response_deserializer=iwf__pb2.InvokeExecuteMethodResponse.FromString,
                _registered_method=True)
        self.InvokeWorkerRPC = channel.unary_unary(
                '/iwf.WorkerService/InvokeWorkerRPC',
                request_serializer=iwf__pb2.InvokeWorkerRPCRequest.SerializeToString,
                response_deserializer=iwf__pb2.InvokeWorkerRPCResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Hosted by iWF worker; server calls these RPCs.
    """

    def InvokeWaitForMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeExecuteMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeWorkerRPC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InvokeWaitForMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeWaitForMethod,
                    request_deserializer=iwf__pb2.InvokeWaitForMethodRequest.FromString,
                    response_serializer=iwf__pb2.InvokeWaitForMethodResponse.SerializeToString,
            ),
            'InvokeExecuteMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeExecuteMethod,
                    request_deserializer=iwf__pb2.InvokeExecuteMethodRequest.FromString,
                    response_serializer=iwf__pb2.InvokeExecuteMethodResponse.SerializeToString,
            ),
            'InvokeWorkerRPC': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeWorkerRPC,
                    request_deserializer=iwf__pb2.InvokeWorkerRPCRequest.FromString,
                    response_serializer=iwf__pb2.InvokeWorkerRPCResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iwf.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iwf.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Hosted by iWF worker; server calls these RPCs.
    """

    @staticmethod
    def InvokeWaitForMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.WorkerService/InvokeWaitForMethod',
            iwf__pb2.InvokeWaitForMethodRequest.SerializeToString,
            iwf__pb2.InvokeWaitForMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeExecuteMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.WorkerService/InvokeExecuteMethod',
            iwf__pb2.InvokeExecuteMethodRequest.SerializeToString,
            iwf__pb2.InvokeExecuteMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeWorkerRPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iwf.WorkerService/InvokeWorkerRPC',
            iwf__pb2.InvokeWorkerRPCRequest.SerializeToString,
            iwf__pb2.InvokeWorkerRPCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
